--CREATE departments table (has no dependents)
CREATE TABLE departments (
  dept_id INTEGER primary key generated by default as identity,
  dept_name text
);

--CREATE employees table (has no dependents)
CREATE TABLE employees (
  emp_id INTEGER primary key generated by default as identity,
  emp_name text,
);

--CREATE employee_department table with foreign keys from departments and employees
CREATE TABLE employee_department (
    emp_id INTEGER REFERENCES employees(emp_id),
    dept_id INTEGER REFERENCES departments(dept_id),
    PRIMARY KEY (emp_id, dept_id)
);